name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js and Install Server Dependencies
      run: |
        cd ./server
        npm ci
      shell: bash

    - name: Build and Test Server
      run: |
        cd ./server
        npm run build --if-present
      shell: bash

    - name: Setup Node.js and Install Client Dependencies
      run: |
        cd ./client
        npm ci
      shell: bash

