name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build-server:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js for Server
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        working-directory: ./server

      - name: Install Server Dependencies
        run: npm ci
        working-directory: ./server

      - name: Build and Test Server
        run: npm run build --if-present
        working-directory: ./server

  build-client:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js for Client
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        working-directory: ./client

      - name: Install Client Dependencies
        run: npm ci
        working-directory: ./client
